version: "2"
services:
    crawler:
        build : .
        ports: 
            - "3093:3093"
        healthcheck: 
            test: curl --fail http://localhost:3093 || exit 1
            interval: 60s
            timeout: 5s
            retries: 3
            start_period: 10s
        restart: unless-stopped
        depends_on:
            - db
        volumes:
            - .:/app/
            - ./node_modules/:/app/node_modules
        command: 
            - /bin/sh
            - -c
            - |
                npm install mysql --save
                nodemon index.js
        networks:
            - default
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            LANGGENG_API_URL: host.docker.internal
            HARDCODED_CODE_USERCOMM: 9a25c2ce-eafc-47da-98b7-75e3a5b43666
            HARDCODED_USER_ID: 20
            HOST_DB_WALANGGENG: db
            USER_DB_WALANGGENG: user1
            PASS_DB_WALANGGENG: test
            SCHEMA_DB_WALANGGENG: walanggeng
            PORT_DB_WALANGGENG: 3306
            WATZAP_API_URL: https://api.watzap.id/v1
            WATZAP_SANUMBERKEY: HkaerOiLIoUw6Xk6
            WATZAP_APIKEY: KOXIJT9ZXEQ29RLX
            SUPERVISOR_NUMBER_1: 081585002225
            SUPERVISOR_NUMBER_2: 082216182618
    db:
        # image: mysql:8.0
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        ports: 
            - "3307:3306"
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    autoheal:
        restart: always
        image: willfarrell/autoheal
        environment:
        - AUTOHEAL_CONTAINER_LABEL=all
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
volumes:
    persistent: