version: "2"
services:
    crawler:
        build : .
        ports: 
            - "3093:3093"
        volumes:
            - .:/app/
            - ./node_modules/:/app/node_modules
        command: 
            - /bin/sh
            - -c
            - |
                npm install
                nodemon index.js
        environment:
            HOST_DB_LANGGENG: host.docker.internal
            USER_DB_LANGGENG: user
            PASS_DB_LANGGENG: test
            SCHEMA_DB_LANGGENG: laravel
            WATZAP_API_URL: https://api.watzap.id/v1
            WATZAP_SANUMBERKEY: HkaerOiLIoUw6Xk6
            WATZAP_APIKEY: KOXIJT9ZXEQ29RLX
            SUPERVISOR_NUMBER_1: 081585002225
            SUPERVISOR_NUMBER_2: 082216182618